/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as AppAppProfileRouteImport } from './routes/_app.app.profile'
import { Route as AppAppDashboardRouteImport } from './routes/_app.app.dashboard'
import { Route as AppAppCategoriesRouteImport } from './routes/_app.app.categories'
import { Route as AppAppProductsIndexRouteImport } from './routes/_app.app.products.index'
import { Route as AppAppProductsNewRouteImport } from './routes/_app.app.products.new'
import { Route as AppAppProductsProductIdIndexRouteImport } from './routes/_app.app.products.$productId.index'
import { Route as AppAppProductsProductIdEditRouteImport } from './routes/_app.app.products.$productId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProfileRoute = AppAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAppDashboardRoute = AppAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAppCategoriesRoute = AppAppCategoriesRouteImport.update({
  id: '/app/categories',
  path: '/app/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProductsIndexRoute = AppAppProductsIndexRouteImport.update({
  id: '/app/products/',
  path: '/app/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProductsNewRoute = AppAppProductsNewRouteImport.update({
  id: '/app/products/new',
  path: '/app/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProductsProductIdIndexRoute =
  AppAppProductsProductIdIndexRouteImport.update({
    id: '/app/products/$productId/',
    path: '/app/products/$productId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppProductsProductIdEditRoute =
  AppAppProductsProductIdEditRouteImport.update({
    id: '/app/products/$productId/edit',
    path: '/app/products/$productId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/categories': typeof AppAppCategoriesRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/': typeof AppAppIndexRoute
  '/app/products/new': typeof AppAppProductsNewRoute
  '/app/products/': typeof AppAppProductsIndexRoute
  '/app/products/$productId/edit': typeof AppAppProductsProductIdEditRoute
  '/app/products/$productId/': typeof AppAppProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/categories': typeof AppAppCategoriesRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app': typeof AppAppIndexRoute
  '/app/products/new': typeof AppAppProductsNewRoute
  '/app/products': typeof AppAppProductsIndexRoute
  '/app/products/$productId/edit': typeof AppAppProductsProductIdEditRoute
  '/app/products/$productId': typeof AppAppProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/app/categories': typeof AppAppCategoriesRoute
  '/_app/app/dashboard': typeof AppAppDashboardRoute
  '/_app/app/profile': typeof AppAppProfileRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/products/new': typeof AppAppProductsNewRoute
  '/_app/app/products/': typeof AppAppProductsIndexRoute
  '/_app/app/products/$productId/edit': typeof AppAppProductsProductIdEditRoute
  '/_app/app/products/$productId/': typeof AppAppProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/'
    | '/app/products/new'
    | '/app/products/'
    | '/app/products/$productId/edit'
    | '/app/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/profile'
    | '/app'
    | '/app/products/new'
    | '/app/products'
    | '/app/products/$productId/edit'
    | '/app/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/app/categories'
    | '/_app/app/dashboard'
    | '/_app/app/profile'
    | '/_app/app/'
    | '/_app/app/products/new'
    | '/_app/app/products/'
    | '/_app/app/products/$productId/edit'
    | '/_app/app/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/profile': {
      id: '/_app/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/dashboard': {
      id: '/_app/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppAppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/categories': {
      id: '/_app/app/categories'
      path: '/app/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppAppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/products/': {
      id: '/_app/app/products/'
      path: '/app/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppAppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/products/new': {
      id: '/_app/app/products/new'
      path: '/app/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AppAppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/products/$productId/': {
      id: '/_app/app/products/$productId/'
      path: '/app/products/$productId'
      fullPath: '/app/products/$productId/'
      preLoaderRoute: typeof AppAppProductsProductIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/products/$productId/edit': {
      id: '/_app/app/products/$productId/edit'
      path: '/app/products/$productId/edit'
      fullPath: '/app/products/$productId/edit'
      preLoaderRoute: typeof AppAppProductsProductIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppCategoriesRoute: typeof AppAppCategoriesRoute
  AppAppDashboardRoute: typeof AppAppDashboardRoute
  AppAppProfileRoute: typeof AppAppProfileRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppProductsNewRoute: typeof AppAppProductsNewRoute
  AppAppProductsIndexRoute: typeof AppAppProductsIndexRoute
  AppAppProductsProductIdEditRoute: typeof AppAppProductsProductIdEditRoute
  AppAppProductsProductIdIndexRoute: typeof AppAppProductsProductIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppCategoriesRoute: AppAppCategoriesRoute,
  AppAppDashboardRoute: AppAppDashboardRoute,
  AppAppProfileRoute: AppAppProfileRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppProductsNewRoute: AppAppProductsNewRoute,
  AppAppProductsIndexRoute: AppAppProductsIndexRoute,
  AppAppProductsProductIdEditRoute: AppAppProductsProductIdEditRoute,
  AppAppProductsProductIdIndexRoute: AppAppProductsProductIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
